### ISSUE TITLE
Ugly mobile Google Ads

### ISSUE THREAD

**Issue by ogorzalka** [mertJF/tailblocks#103]
Hi,

I know that money is everything but the ad is particularly annoying on mobile

![60B92CF8-BC71-4F83-A5BC-C09B3512E269](https://user-images.githubusercontent.com/149651/190862341-deae9061-525b-460f-9c1e-8975fbd13b98.jpeg)

Too bad because the project is really interesting.

**Comment by codewithnuh** [comment]
I can fix it
