### ISSUE TITLE
Suggestion: Add proper labels to form inputs and textareas

### ISSUE THREAD

**Issue by cahva** [mertJF/tailblocks#11]
Hi,

It's (generally) a bad idea to use placeholder acting as a label and this caught my eye on otherwise very nice templates. I know they look "sweet" with only placeholders but sacrifices usablity and teach bad habits. 

IMO those inputs and textareas in those templates look sweet with only labels anyway :)

**Comment by saini-g** [comment]
Hi,
If this is still open for work I'd like to work on it. Is there a protocol or contributing guide?

**Comment by mertJF** [comment]
We'll work on this, thank you for your suggestion.

**Comment by saini-g** [comment]
@mertJF how can I run this locally? I'm getting an error when running `npm install`
![tailblock-npm install error](https://user-images.githubusercontent.com/50542972/83225418-57036880-a19d-11ea-9448-c1a358573ca2.png)

**Comment by aryavb** [comment]
It worked for me earlier today. Try updating Node/NPM.

**Comment by saini-g** [comment]
I've added a PR for this
https://github.com/mertJF/tailblocks/pull/19
Please let me know if any changes are needed
