### ISSUE TITLE
suggestion: add search

### ISSUE THREAD

**Issue by TBD** [mertJF/tailblocks#12]
similar to https://tailwindcss.com/ - accesible via keyboard shortcut (eg "/") to quickly jump to blocks

**Comment by saini-g** [comment]
Although the shortcut does sound nice, I think it will need JS to be implemented fully.
One option for adding a shortcut without any JS login is the global [`accesskey`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey) attribute but as seen in the docs, the usage varies widely across browsers and operating systems.
