### ISSUE TITLE
Add option to copy as JSX as well as HTML

### ISSUE THREAD

**Issue by brandonpittman** [mertJF/tailblocks#17]
Could be nice to have a "Copy as JSX" button alongside a "Copy as HTML" button.

https://github.com/mertJF/tailblocks/blob/2c321175c6cc03f741cb146779c4bdfd5f916aee/src/App.js#L301-L315

Happy to work on a PR if you're open to it.

**Comment by mertJF** [comment]
Hi @brandonpittman, I think this is a good idea. But I don't plan to work on this for now.
