### ISSUE TITLE
the dark / light switch on demo website should be instant. 

### ISSUE THREAD

**Issue by delata** [mertJF/tailblocks#20]
it takes more than a seconds. and lags. it should me smooth.

**Comment by aryavb** [comment]
It seems to be instantaneous for me on the latest versions of Chrome, Firefox, and Safari on MacOS.

**Comment by aryavb** [comment]
@delata It seems to be instantaneous for me on the latest versions of Chrome, Firefox, and Safari on MacOS. Would you mind showing a video?

**Comment by delata** [comment]
i am using chrome ( actually Brave) on android running on a 75 dollar phone.

**Comment by mr-winson** [comment]
I don't mean to be rude but that might be why.

**Comment by delata** [comment]
again you are running on a macbook.
yes on my laptop lag is less noticeable.
 test this on a low powered phone.

**Comment by Anachron** [comment]
I'm running it on a Samsung Galaxy A40 which costes $150 when it was new a year ago but it takes at most a second to change.

Are you sure it is not causes by addons or other applications slowing down your phone?

Also I'm running it on firefox, maybe try that as well.

**Comment by delata** [comment]
this is a problem, i have used other websites that had this kind of mechanism, but they were smooth on my phone.

**Comment by Anachron** [comment]
Were they also written in react or just switched stylesheets?

**Comment by delata** [comment]
i don't know, they were simple website.  the whole react thing is a garbage. worse thing is that people are now using it every where.

**Comment by aryavb** [comment]
@delata I see what you're talking about: [6x Slowed CPU + 3G](https://streamable.com/9ajnj4), but I believe this is just the result of making large changes to the DOM on slower devices. I think a solution could be to maybe make the opposite version (dark/light) hidden instead of completely removed from the DOM; however, this feels like an edge case.

**Comment by aryavb** [comment]
> Were they also written in react or just switched stylesheets?

They're two separate React components which are removed and added with the switch, which causes quite a bit of distress to the CPU, etc.. Only around 10 classes are changed, so I can see possible merging these two components into one, but it will reduce readability of the source code.

**Comment by Anachron** [comment]
> > Were they also written in react or just switched stylesheets?
> 
> They're two separate React components which are removed and added with the switch, which causes quite a bit of distress to the CPU, etc.. Only around ten CSS classes are changed, so I can see possible merging these two components into one, but it will reduce readability of the source code.
I was talking about the other websites, if they were switching stylesheets or also are written in react. I am well aware how this library handles it, given that I've read the source code.

**Comment by aryavb** [comment]
@Anachron Sorry, I guess I misread it.
