### ISSUE TITLE
Navbar Examples

### ISSUE THREAD

**Issue by Jufik** [mertJF/tailblocks#21]
Do you plan adding mode complexity to navbars ?
By complexity I mean: Use a burger in responsive mode, dropdowns-on-hover, an "account like" exemple?

I realize those can lead to super opinionated choices, but it's often required in real world products.

**Comment by mertJF** [comment]
Hi @Jufik, I am not considering adding javascript into the blocks to create navbar/dropdown menus, etc. for now. Thank you.
