### ISSUE TITLE
Can you please use Github "Releases" so I can subscribe only to it using "Releases only"?

### ISSUE THREAD

**Issue by frederikhors** [mertJF/tailblocks#25]
Can you please use Github "Releases" so I can subscribe only to it using "Releases only"?

I'm receiving many emails using the simple "Watch".

Thank you.

**Comment by mertJF** [comment]
Thank you for your advice, I've changed the notification settings.

**Comment by frederikhors** [comment]
I don't understand. Are you gonna to use Releases?

**Comment by mertJF** [comment]
Yes, I will use Releases, I need to make some improvements to create first one.
