### ISSUE TITLE
Question: How did you make the graphics for the left sidebar

### ISSUE THREAD

**Issue by xzava** [mertJF/tailblocks#27]
The preview html graphics for the leftside bar, how did you make them?

Did you use a library or service or did you make them my hand.

Thanks

**Comment by saini-g** [comment]
The preview icons are all inline svgs. I don't know how those were created but my go to tool for svg creation is [Figma](https://www.figma.com/), very easy to use and feature rich. For individual developers the free version is perfect.

**Comment by mertJF** [comment]
I've used Figma to create icons. You can reach them from the following link.

https://www.figma.com/file/RlSJQcJuEx3FseHT10Sx4v/tailblocks?node-id=19%3A39
