### ISSUE TITLE
Add Responsive Header in Navigation Header for Mobile screens 

### ISSUE THREAD

**Issue by nikhilm19** [mertJF/tailblocks#39]
Right now the mobile preview of the Header templates doesnt look quite good. Can enhance by collapsing to a hamburger menu like the website itself has right now 

Awesome work though!

**Comment by luis-cruzt** [comment]
This enhancement would be great!

**Comment by mertJF** [comment]
Hello @nikhilm19,

This implementation needs a little bit of JavaScript. 
I've no plan to add JavaScript into the blocks. Thank you for your interest.
