### ISSUE TITLE
Floating Labels in Contact Form.

### ISSUE THREAD

**Issue by ShubhamVerma1811** [mertJF/tailblocks#41]
The form doesn't have any labels.
It would be nice to have floating labels on them.

**Comment by mohitm15** [comment]
@ShubhamVerma1811 Can you specify which forms you are talking about and attach any example screenshot?

**Comment by ShubhamVerma1811** [comment]
Hey @mohitm15,
Wow this has been inactive for 2 years.
Anyways, all the forms on Tailblocks lack placeholder.
Having floating labels would work great in this case.

Tailwind provides `peer` and `peer-placeholder-shown` classes which can be used for floating labels.
I've build something similar for my website here https://shubhamverma.me/books. 
Clicking on "Suggest me a book" would show up forms with floating label.

Same thing could also be implemented in Tailblocks.

**Comment by ShubhamVerma1811** [comment]
Hey @mohitm15,
Wow this has been inactive for 2 years.
Anyways, all the forms on Tailblocks lack placeholder.
Having floating labels would work great in this case.

Tailwind provides `peer` and `peer-placeholder-shown` classes which can be used for floating labels.
I've build something similar for my website here https://shubhamverma.me/books. 
Clicking on "Suggest me a book" would show up forms with floating label.

Same thing could also be implemented in Tailblocks.

Edit: This video also helps
https://www.youtube.com/watch?v=nJzKi6oIvBA

**Comment by mohitm15** [comment]
Hey @ShubhamVerma181,
Sorry for the late reply; I had implemented the change with the tailwind CSS over tailwind play [here](https://play.tailwindcss.com/zWbcoonqTl) .

But I could not reproduce it in the react component say `contact/dark/c.js` because the `peer-placeholder-shown` classes are not working there. I had used the CSS to produce that behavior but still not getting it.

**Comment by ShubhamVerma1811** [comment]
@mohitm15 , It might not be working because this project is using a really old version of Tailwind.
https://github.com/mertJF/tailblocks/blob/master/public/index.html#L12

Tailwind has there own CDN now, https://tailwindcss.com/docs/installation/play-cdn

I dont think if this project is actively maintained now by the author.

**Comment by mohitm15** [comment]
Yes @ShubhamVerma1811 , it is using an old version of tailwind and unfortunately has also not been maintained by the owner now :disappointed:
