### ISSUE TITLE
Not able to veiw the code in iPhone 7+

### ISSUE THREAD

**Issue by Abood025** [mertJF/tailblocks#49]
I dont know why , but i dont have the option to veiw code in 
https://mertjf.github.io/tailblocks
Please make it available for those devices

**Comment by noxify** [comment]
It seems that the "view code" button is hidden on mobile screens.

Workaround: reducing the text size in the mobile safari to 50% and you can see the button ;) 

Tested it on my iPhone 7+ and it works :)
