### ISSUE TITLE
Patreon veya diğer destek kanalları

### ISSUE THREAD

**Issue by cenksener** [mertJF/tailblocks#6]
Eline emeğine sağlık hocam. Tailwindui ı satın aldım. İnanki adamlar senin kadar component sunmadılar. Update gelecek diye 30 gün bekliyoruz. 30 gün sonunda 2 tane header falan ekliyorlar projeye :) En son 6 mayısta guncellediler. Sonra, 1 hafta sonra tekrar guncelleme olacak dediler. 3 hafta geçti hala beklioruz.

Tek seferlik destek veya patreon linkin varsa, tailwindui ın discord grubunda paylasayim.

**Comment by mertJF** [comment]
Öncelikle ilgin için teşekkür ederim :) Bu componentleri/blockları yaparken tamamiyle Tailwind CSS'i biraz kurcalamak için girişmiştim epey hızlı yapılabildiğini görünce birkaç block daha yapıp bunları paylaşayım düşündüm maddi bir beklentim teklifin için de teşekkür ederim :)
