### ISSUE TITLE
Undefined macros like title-font

### ISSUE THREAD

**Issue by ykurtbas** [mertJF/tailblocks#63]
You have macros like `title-font` and `body-font` in your templates. Makes copy pasting into scss very hard since those doesn't exist in our templates.

**Comment by johtso** [comment]
Just got bitten by this today, PostCSS was rightfully complaining that it wasn't defined. Had me searching around trying to figure out if it was something that only existed in an older version of tailwind or something..

**Comment by mertJF** [comment]
I have added the classes to change typography easily. Of course, you can remove that from blocks if you want. These classes are not necessary.
