### ISSUE TITLE
CMS Suggestions

### ISSUE THREAD

**Issue by reavpC6K** [mertJF/tailblocks#79]
What's a nice way to assemble a static site from tailblocks and save the files locally, besides using a text editor?

**Comment by CyberDudeJ** [comment]
Using the novi editor

**Comment by CyberDudeJ** [comment]
it's on codecanyon.net

**Comment by reavpC6K** [comment]
Very cool!
Since opening this issue I discovered [Destack](https://github.com/LiveDuo/destack), it uses TailBlocks directly.
