### ISSUE TITLE
CSS Doesn't function

### ISSUE THREAD

**Issue by CyberDudeJ** [mertJF/tailblocks#83]
When I copy and paste it, it then doesn;t even paste at all!

**Comment by k-rite** [comment]
You have to add [tailwind ](https://tailwindcss.com/docs/installation
)first.

**Comment by PranavDeveloper-FullStack** [comment]
You will have to add this link to your html code then it will work 
`<link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">`

**Comment by CyberDudeJ** [comment]
Thanks
